#!/usr/bin/env bash
# Wire EXPO_PUBLIC_SENTRY_DSN for local + optional EAS (N-OPS-01).
# Usage:
#   ./scripts/set-sentry-dsn.sh 'https://KEY@oORG.ingest.sentry.io/PROJECT'
#   ./scripts/set-sentry-dsn.sh   # prompts
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

DSN="${1:-}"
if [[ -z "$DSN" ]]; then
  echo "Paste Sentry Client DSN (https://…@o….ingest.sentry.io/…):"
  read -r DSN
fi
if [[ ! "$DSN" =~ ^https://.+@o[0-9]+\.ingest\.sentry\.io/[0-9]+ ]]; then
  echo "DSN does not look like a Sentry client key. Aborting."
  exit 1
fi

# .env.local (gitignored) for Metro / expo run
{
  echo "# Generated by scripts/set-sentry-dsn.sh — do not commit"
  echo "EXPO_PUBLIC_SENTRY_DSN=$DSN"
} > .env.local
echo "Wrote .env.local"

# EAS preview + production env (sensitive) for distributed builds
if command -v npx >/dev/null; then
  echo "Pushing to EAS env (preview + production) as sensitive…"
  npx eas-cli env:create --name EXPO_PUBLIC_SENTRY_DSN --value "$DSN" --type sensitive --environment preview --force 2>/dev/null \
    || npx eas-cli env:create --name EXPO_PUBLIC_SENTRY_DSN --value "$DSN" --type sensitive --environment preview || true
  npx eas-cli env:create --name EXPO_PUBLIC_SENTRY_DSN --value "$DSN" --type sensitive --environment production --force 2>/dev/null \
    || npx eas-cli env:create --name EXPO_PUBLIC_SENTRY_DSN --value "$DSN" --type sensitive --environment production || true
fi

echo ""
echo "Next:"
echo "  1. Debug verify: EXPO_PUBLIC_SENTRY_DSN='$DSN' npx expo run:ios --device"
echo "  2. Open PlayingHost → tap Crash chip → confirm Issue in Sentry"
echo "  3. Fill docs/ops/CRASH-REPORTING.md verification log"
